package rest

const (
	sourceRef      = "133d385dfbee06825d4d4136a82dd2b4c79813ba"
	sourceChecksum = "sha256:93b14ec8053fde77ac78837e73db9346e3f8802fb4bf4b801ff4269dad89c4ca"
)

var openAPISource = Source{
	Name:     "github/rest-api-description",
	Ref:      sourceRef,
	URL:      "https://raw.githubusercontent.com/github/rest-api-description/" + sourceRef + "/descriptions/api.github.com/api.github.com.json",
	Checksum: sourceChecksum,
}

var pagePagination = Pagination{
	Style:        "page",
	PageParam:    "page",
	PerPageParam: "per_page",
	MaxPerPage:   100,
	Notes:        "Use --paginate to follow Link headers.",
}

var noPagination = Pagination{
	Style: "none",
}

var repoPathParams = []Parameter{
	{Name: "owner", In: "path", Type: "string", Required: true, Description: "Repository owner."},
	{Name: "repo", In: "path", Type: "string", Required: true, Description: "Repository name without the .git extension."},
}

var operations = []Operation{
	{
		OperationID: "actions/get-pending-deployments-for-run",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/actions/runs/{run_id}/pending_deployments",
		Tag:         "actions",
		Summary:     "Get pending deployments for a workflow run",
		DocsURL:     "https://docs.github.com/rest/actions/workflow-runs#get-pending-deployments-for-a-workflow-run",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token for private repositories)", "Actions:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "run_id", In: "path", Type: "integer", Required: true, Description: "Workflow run id."},
		),
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx env pending",
			Notes:           "First-class workflow should explain blocked environment protection requests.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "actions/get-hosted-runners-limits-for-org",
		Method:      "GET",
		Path:        "/orgs/{org}/actions/hosted-runners/limits",
		Tag:         "actions",
		Summary:     "Get limits on GitHub-hosted runners for an organization",
		DocsURL:     "https://docs.github.com/rest/actions/hosted-runners#get-limits-on-github-hosted-runners-for-an-organization",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"manage_runner:org (classic token)"},
		Parameters: []Parameter{
			{Name: "org", In: "path", Type: "string", Required: true, Description: "Organization name."},
		},
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "missing",
			ProposedCommand: "ghx runners capacity",
			Notes:           "Useful for diagnosing hosted runner capacity and account limits.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "actions/list-hosted-runners-for-org",
		Method:      "GET",
		Path:        "/orgs/{org}/actions/hosted-runners",
		Tag:         "actions",
		Summary:     "List GitHub-hosted runners for an organization",
		DocsURL:     "https://docs.github.com/rest/actions/hosted-runners#list-github-hosted-runners-for-an-organization",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"manage_runner:org (classic token)"},
		Parameters: []Parameter{
			{Name: "org", In: "path", Type: "string", Required: true, Description: "Organization name."},
			{Name: "per_page", In: "query", Type: "integer", Description: "Results per page, max 100."},
			{Name: "page", In: "query", Type: "integer", Description: "Page number to fetch."},
		},
		Pagination: pagePagination,
		Coverage: Coverage{
			State:           "missing",
			ProposedCommand: "ghx runners status",
			Notes:           "No first-class command lists hosted runner ids, names, and images.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "actions/list-jobs-for-workflow-run",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/actions/runs/{run_id}/jobs",
		Tag:         "actions",
		Summary:     "List jobs for a workflow run",
		DocsURL:     "https://docs.github.com/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token for private repositories)", "Actions:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "run_id", In: "path", Type: "integer", Required: true, Description: "Workflow run id."},
			Parameter{Name: "filter", In: "query", Type: "string", Enum: []string{"latest", "all"}, Description: "Filter check runs by completed_at timestamp."},
			Parameter{Name: "per_page", In: "query", Type: "integer", Description: "Results per page, max 100."},
			Parameter{Name: "page", In: "query", Type: "integer", Description: "Page number to fetch."},
		),
		Pagination: pagePagination,
		Coverage: Coverage{
			State:           "thin",
			LocalCommand:    "ghx run view",
			ProposedCommand: "ghx checks inventory",
			Notes:           "Existing run views show jobs, but agents still need cross-PR inventory output.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "actions/list-workflow-run-artifacts",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/actions/runs/{run_id}/artifacts",
		Tag:         "actions",
		Summary:     "List workflow run artifacts",
		DocsURL:     "https://docs.github.com/rest/actions/artifacts#list-workflow-run-artifacts",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token for private repositories)", "Actions:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "run_id", In: "path", Type: "integer", Required: true, Description: "Workflow run id."},
			Parameter{Name: "per_page", In: "query", Type: "integer", Description: "Results per page, max 100."},
			Parameter{Name: "page", In: "query", Type: "integer", Description: "Page number to fetch."},
			Parameter{Name: "name", In: "query", Type: "string", Description: "Artifact name filter."},
			Parameter{Name: "direction", In: "query", Type: "string", Enum: []string{"asc", "desc"}, Description: "Sort direction."},
		),
		Pagination: pagePagination,
		Coverage: Coverage{
			State:           "thin",
			LocalCommand:    "ghx run download",
			ProposedCommand: "ghx actions storage report",
			Notes:           "Existing command downloads artifacts but does not inventory cost or retention risk.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "actions/review-pending-deployments-for-run",
		Method:      "POST",
		Path:        "/repos/{owner}/{repo}/actions/runs/{run_id}/pending_deployments",
		Tag:         "actions",
		Summary:     "Review pending deployments for a workflow run",
		DocsURL:     "https://docs.github.com/rest/actions/workflow-runs#review-pending-deployments-for-a-workflow-run",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token)", "Actions:write (fine-grained repository token)", "Deployments:write (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "run_id", In: "path", Type: "integer", Required: true, Description: "Workflow run id."},
			Parameter{Name: "environment_ids", In: "body", Type: "array", Required: true, Description: "Environment ids to approve or reject.", Example: "161171787"},
			Parameter{Name: "state", In: "body", Type: "string", Required: true, Enum: []string{"approved", "rejected"}, Description: "Whether to approve or reject deployment.", Example: "approved"},
			Parameter{Name: "comment", In: "body", Type: "string", Required: true, Description: "Deployment review comment.", Example: "reviewed"},
		),
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx env approve, ghx env reject",
			Notes:           "First-class command should dry-run by default and show exact environment ids.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "checks/list-for-ref",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/commits/{ref}/check-runs",
		Tag:         "checks",
		Summary:     "List check runs for a Git reference",
		DocsURL:     "https://docs.github.com/rest/checks/runs#list-check-runs-for-a-git-reference",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token for private repositories)", "Checks:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "ref", In: "path", Type: "string", Required: true, Description: "Commit SHA, branch name, or tag name."},
			Parameter{Name: "check_name", In: "query", Type: "string", Description: "Check run name filter."},
			Parameter{Name: "status", In: "query", Type: "string", Enum: []string{"queued", "in_progress", "completed"}, Description: "Check run status filter."},
			Parameter{Name: "filter", In: "query", Type: "string", Enum: []string{"latest", "all"}, Description: "Filter check runs by completed_at timestamp."},
			Parameter{Name: "per_page", In: "query", Type: "integer", Description: "Results per page, max 100."},
			Parameter{Name: "page", In: "query", Type: "integer", Description: "Page number to fetch."},
			Parameter{Name: "app_id", In: "query", Type: "integer", Description: "GitHub App id filter."},
		),
		Pagination: pagePagination,
		Coverage: Coverage{
			State:           "thin",
			LocalCommand:    "ghx pr checks",
			ProposedCommand: "ghx pr gate explain, ghx checks inventory",
			Notes:           "Existing commands expose checks but do not explain merge gate blockers across refs.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "checks/rerequest-run",
		Method:      "POST",
		Path:        "/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest",
		Tag:         "checks",
		Summary:     "Rerequest a check run",
		DocsURL:     "https://docs.github.com/rest/checks/runs#rerequest-a-check-run",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token for private repositories)", "Checks:write (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "check_run_id", In: "path", Type: "integer", Required: true, Description: "Check run id."},
		),
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx checks rerun --dry-run",
			Notes:           "First-class command should select failed checks intentionally instead of rerunning whole workflows.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "checks/rerequest-suite",
		Method:      "POST",
		Path:        "/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest",
		Tag:         "checks",
		Summary:     "Rerequest a check suite",
		DocsURL:     "https://docs.github.com/rest/checks/suites#rerequest-a-check-suite",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo (classic token for private repositories)", "Checks:write (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "check_suite_id", In: "path", Type: "integer", Required: true, Description: "Check suite id."},
		),
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx checks rerun --dry-run",
			Notes:           "Suite reruns should stay explicit because they can fan out large CI work.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "repos/create-deployment-status",
		Method:      "POST",
		Path:        "/repos/{owner}/{repo}/deployments/{deployment_id}/statuses",
		Tag:         "repos",
		Summary:     "Create a deployment status",
		DocsURL:     "https://docs.github.com/rest/deployments/statuses#create-a-deployment-status",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo_deployment (classic token)", "Deployments:write (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "deployment_id", In: "path", Type: "integer", Required: true, Description: "Deployment id."},
			Parameter{Name: "state", In: "body", Type: "string", Required: true, Enum: []string{"error", "failure", "inactive", "in_progress", "queued", "pending", "success"}, Description: "Deployment status state.", Example: "success"},
			Parameter{Name: "target_url", In: "body", Type: "string", Description: "Target URL for deployment output."},
			Parameter{Name: "log_url", In: "body", Type: "string", Description: "Log URL for deployment output."},
			Parameter{Name: "description", In: "body", Type: "string", Description: "Short status description."},
			Parameter{Name: "environment", In: "body", Type: "string", Description: "Deployment environment name."},
			Parameter{Name: "environment_url", In: "body", Type: "string", Description: "URL for accessing the environment."},
			Parameter{Name: "auto_inactive", In: "body", Type: "boolean", Description: "Whether to auto-inactivate prior deployments."},
		),
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx deploy status",
			Notes:           "First-class command should keep status mutation inspectable and dry-run friendly.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "repos/get-deployment",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/deployments/{deployment_id}",
		Tag:         "repos",
		Summary:     "Get a deployment",
		DocsURL:     "https://docs.github.com/rest/deployments/deployments#get-a-deployment",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo_deployment (classic token for private repositories)", "Deployments:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "deployment_id", In: "path", Type: "integer", Required: true, Description: "Deployment id."},
		),
		Pagination: noPagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx deploy timeline",
			Notes:           "Raw operation is useful until deployment timeline aggregation lands.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "repos/list-deployment-statuses",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/deployments/{deployment_id}/statuses",
		Tag:         "repos",
		Summary:     "List deployment statuses",
		DocsURL:     "https://docs.github.com/rest/deployments/statuses#list-deployment-statuses",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo_deployment (classic token for private repositories)", "Deployments:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "deployment_id", In: "path", Type: "integer", Required: true, Description: "Deployment id."},
			Parameter{Name: "per_page", In: "query", Type: "integer", Description: "Results per page, max 100."},
			Parameter{Name: "page", In: "query", Type: "integer", Description: "Page number to fetch."},
		),
		Pagination: pagePagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx deploy timeline",
			Notes:           "Timeline command should join deployment and status history.",
		},
		Source: openAPISource,
	},
	{
		OperationID: "repos/list-deployments",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/deployments",
		Tag:         "repos",
		Summary:     "List deployments",
		DocsURL:     "https://docs.github.com/rest/deployments/deployments#list-deployments",
		APIVersion:  DefaultAPIVersion,
		Scopes:      []string{"repo_deployment (classic token for private repositories)", "Deployments:read (fine-grained repository token)"},
		Parameters: append(append([]Parameter{}, repoPathParams...),
			Parameter{Name: "sha", In: "query", Type: "string", Description: "SHA filter."},
			Parameter{Name: "ref", In: "query", Type: "string", Description: "Ref filter."},
			Parameter{Name: "task", In: "query", Type: "string", Description: "Task filter."},
			Parameter{Name: "environment", In: "query", Type: "string", Description: "Environment filter."},
			Parameter{Name: "per_page", In: "query", Type: "integer", Description: "Results per page, max 100."},
			Parameter{Name: "page", In: "query", Type: "integer", Description: "Page number to fetch."},
		),
		Pagination: pagePagination,
		Coverage: Coverage{
			State:           "raw-api",
			ProposedCommand: "ghx deploy timeline",
			Notes:           "No first-class deployment timeline command exists yet.",
		},
		Source: openAPISource,
	},
}
